puma560:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 2000  

# Effort Controllers ---------------------------------------
  joint_1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_1
# Effort Controllers ---------------------------------------
  joint_2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_2
# Effort Controllers ---------------------------------------
  joint_3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_3
# Effort Controllers ---------------------------------------
  joint_4_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_4
# Effort Controllers ---------------------------------------
  joint_5_effort_controller:
    type: effort_controllers/JointEffortController
    joint: joint_5


# Position Controllers ---------------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 1.0, i: 0.0, d: 0.0}
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 2000.0, i: 10.0, d: 100.0}
  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 500.0, i: 5.0, d: 25.0}
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 1.0, i: 0.1, d: 0.1}
  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 1.0, i: 0.1, d: 0.1}
